export const divMasterPage = 'flex flex-col container text-center'
export const divSubmitLoadingMaster = 'flex flex-col w-screen h-screen top-0 left-0 absolute items-center justify-center bg-gray-900/60 dark:bg-gray-800/50 transition-all duration-300'
export const divSubmitLoadingCard = 'flex flex-col items-center p-40 rounded-3xl bg-gray-900/80 dark:bg-gray-900/90'
export const divItemsForm = 'flex gap-2 items-center'
export const divCheckboxItem = 'flex justify-center items-center gap-2 mt-6'
export const divSubmitResetItems = 'flex gap-2 mt-4'
export const divDescriptionCardMaster = 'flex gap-2 items-center justify-center mt-2'
export const divDescriptionCardMasterWrap = 'flex flex-wrap gap-4 justify-center'
export const divDescriptionInsertCurriculumCardItem = 'flex flex-col w-2/6 items-left p-4 my-4 gap-6 bg-white/50 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl text-left'
export const divDescriptionCurriculumCardItemError = 'flex flex-col items-center p-4 mb-4 gap-6 bg-red-500/50 dark:bg-red-800/70 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl text-left'
export const divDescriptionCurriculumCardItem = 'flex flex-col items-center p-4 mb-4 gap-6 bg-white/50 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl text-left'
export const divDatePicker = 'flex w-3/4'
export const divWithDoubleItems = 'flex w-3/4 gap-2'
export const divWithDoubleItemsLeft = 'w-10/12'
export const divWithDoubleItemsRight = 'flex w-2/12 items-center gap-2'
export const divWithDoubleItemsLeftExtended = 'w-10/12'
export const divWithDoubleItemsRightExtended = 'flex w-4/12 items-center gap-2'
export const divPhoneMaster = 'flex w-2/4 gap-2'
export const divPhoneNumber = 'flex w-10/12 items-center gap-1'
export const divDetailsAlternativeBgMaster = 'flex flex-col py-2 gap-2 bg-white/50 dark:bg-gray-800/40 rounded-xl'

export const hrElement = 'pb-4'

export const pageTitleH1 = 'font-bold text-2xl my-4'
export const submitTitleH1 = 'text-xl text-white mb-3'
export const message2xlH1 = 'font-bold text-2xl pb-10 text-red-600 dark:text-yellow-500'
export const messageLgH1 = 'font-bold text-lg py-4 text-red-600 dark:text-yellow-500'
export const messageP = 'text-red-600 dark:text-yellow-500'

export const labelTextError = 'w-1/4 text-right text-red-500 dark:text-red-400'
export const labelTextOk = 'w-1/4 text-right text-gray-900 dark:text-gray-100'
export const labelCheckbox = 'text-sm text-gray-600 dark:text-gray-100'
export const labelTextRight = 'text-right'
export const labelSpan = 'text-sm'
export const labelInputRadio = ''

export const inputError = 'w-3/4 px-2 py-1 dark:bg-gray-800 border dark:text-gray-100 border-red-600 rounded-2xl'
export const inputOk = 'w-3/4 px-2 py-1 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl cursor-default'
export const inputCheckbox = 'ml-1 text-green-500 dark:text-green-500 border-none'
export const inputWithButtonError = 'w-full px-2 py-1 dark:bg-gray-800 border dark:text-gray-100 border-red-600 rounded-2xl'
export const inputWithButtonOk = 'w-full px-2 py-1 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl cursor-default'
export const inputWithButtonDisabled = 'w-full px-2 py-1 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl cursor-default opacity-70'

export const selectError = 'w-3/4 px-2 py-1 dark:bg-gray-800 border dark:text-gray-100 border-red-600 rounded-2xl'
export const selectOk = 'w-3/4 px-2 py-1 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl cursor-default'
export const selectDisabled = 'w-3/4 px-2 py-1 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl cursor-default opacity-70'
export const selectDDDError = 'pr-8 px-2 py-1 dark:bg-gray-800 border dark:text-gray-100 border-red-600 rounded-2xl'
export const selectDDDOk = 'pr-8 px-2 py-1 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl cursor-default'

export const datePickerError = 'px-2 py-1 dark:bg-gray-800 border dark:text-gray-100 border-red-600 rounded-2xl'

export const datePickerOk = 'px-2 py-1 dark:bg-gray-800 border border-transparent dark:border-transparent dark:text-gray-100 rounded-2xl cursor-default'


export const buttonSubmit = 'border rounded-xl border-green-900/10 bg-green-500 disabled:bg-green-500/70 disabled:dark:bg-green-500/40 disabled:border-green-900/10 text-white disabled:dark:text-white/50 w-2/4'
export const buttonSubmitFull = 'border rounded-xl border-green-900/10 bg-green-500 disabled:bg-green-500/70 disabled:dark:bg-green-500/40 disabled:border-green-900/10 text-white disabled:dark:text-white/50 w-full'
export const buttonReset = 'border rounded-xl border-gray-600/20 bg-gray-200 disabled:bg-gray-200/30 disabled:border-gray-600/30 text-gray-600 disabled:text-gray-400 w-2/4'
export const buttonWithInput = 'border rounded-2xl border-blue-900 bg-blue-500 disabled:bg-blue-400 text-white w-2/12'
export const buttonEdit = 'border rounded-2xl mt-2 mb-4 border-orange-900 disabled:border-gray-800 bg-orange-500 disabled:bg-gray-200 text-white disabled:text-gray-500 w-3/4'

export const formMaster = 'flex flex-col w-full gap-2 p-4 rounded-xl bg-gray-700/20 dark:bg-gray-100/10 mt-2'
